### ISSUE TITLE
Local musicgen

### ISSUE THREAD

**Issue by gitihobo** [pietrobolcato/musicgen-endpoint-ableton#7]
I already installed facebookresearch musicgen repo, is there a way we can implement that local install into max for live?

**Comment by pietrobolcato** [comment]
Hey there! You could deploy the sagemaker endpoint in local mode, using the `deployment.ipynb` notebook — and then set the endpoint url to localhost in the M4L device. This method would allow you to use your local GPU instead of a cloud one :) 

You need to clone this repository anyway, there's no plug and play way to integrate it directly with the original musicgen repo as you need a rest API interface for the M4L device to work

**Comment by gitihobo** [comment]
Can you give me a step by step guide to how to do that? I made a venv and git cloned the repo, whats next?

**Comment by pietrobolcato** [comment]
Great! Follow the steps until `step 6`, executing only the `Local` portion of the notebook. Then:

- Create a new conda environment for chalice: `conda env create -n chalice -f envs/chalice.yaml`
- Deploy chalice locally: `cd aws/endpoint/lambda/public_endpoint/ && chalice local`
- In the M4L device, set the URL pointing to localhost, returned from the step before

Hope it helps!

**Comment by gitihobo** [comment]
Thank you, sadly im seeing we need sagemaker, does that mean I need to pay a service to use it?

**Comment by pietrobolcato** [comment]
You only need an AWS account, using Sagemaker in local mode is free as you aren't actually using any cloud resource. The only  cost you might incur is the Docker image published in a private ECR, but you can change `aws/endpoint/container/build_and_publish.sh` to use a public one instead, which comes with 50 GB free per month.

Hope it helps!

**Comment by gitihobo** [comment]
Thank you, this is a great idea but I think it would be way better if it was as easy as drag and drop, is that even possible in actuality?

**Comment by pietrobolcato** [comment]
I am not sure how the implementation details of "as easy as a drag and drop" would look like, feel free to open a PR with your code suggestions

**Comment by pietrobolcato** [comment]
Closing this issue for now, let me know if you need more help / you want to open a PR :)
